#!/usr/bin/env python3
"""Generate the static DCP-Bench Open website from dcp-bench-open.jsonl.

Usage:
    python jsonl_convert.py   # optional, to refresh the jsonl from dataset/
    python generate_site.py

Output: site/ (committed to the repo, deployed to GitHub Pages via Actions).
Requires only the Python standard library.
"""

import html
import json
import re
import shutil
import subprocess
from pathlib import Path

DATASET_JSONL = Path("dcp-bench-open.jsonl")
WEB_SRC = Path("web")
OUTPUT_DIR = Path("site")

REPO_URL = "https://github.com/DCP-Bench/DCP-Bench-Open"
RAW_URL = "https://raw.githubusercontent.com/DCP-Bench/DCP-Bench-Open/main"

TITLE = "DCP-Bench Open"
SUBTITLE = (
    "A collaborative benchmark of Discrete Combinatorial Problems: natural language "
    "descriptions, instances and executable constraint models — with provenance."
)

BADGE_COLORS = {
    "csplib": "#2563eb",
    "hakan_examples": "#059669",
    "cpmpy_examples": "#7c3aed",
    "complex_or": "#d97706",
    "aplai_course": "#db2777",
    "CPMpy": "#0d9488",
    "OR-Tools": "#ea580c",
    "MiniZinc": "#2563eb",
    "hand": "#64748b",
}

FRAMEWORK_KEYWORDS = {
    "CPMpy": ["from cpmpy import", "import cpmpy"],
    "OR-Tools": ["ortools", "from ortools"],
    "MiniZinc": ["minizinc", ".mzn"],
}


def esc(value: str) -> str:
    return html.escape(str(value), quote=True)


REPO_HEAD = ""


def repo_head_short() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=5, check=True,
        ).stdout.strip()
        return out or ""
    except Exception:
        return ""


URL_RE = re.compile(r"https?://[^\s]+")


def linkify(text: str) -> str:
    """Escape text and wrap URLs in anchors."""
    parts = URL_RE.split(esc(text))
    urls = URL_RE.findall(esc(text))
    out = [parts[0]]
    for url in urls:
        out.append(f'<a href="{url}" target="_blank" rel="noopener">{url}</a>')
        out.append(parts[urls.index(url) + 1])
    return "".join(out)


def parse_metadata(metadata: list) -> dict:
    fields = {}
    for line in metadata:
        m = re.match(r"#\s*([A-Za-z][A-Za-z ]*?)\s*:\s*(.*)$", line.strip())
        if m:
            key = m.group(1).strip().lower().replace(" ", "_")
            fields[key] = m.group(2).strip()
    return fields


def detect_frameworks(model_code: str) -> list:
    found = []
    for fw, keywords in FRAMEWORK_KEYWORDS.items():
        if any(k in model_code for k in keywords):
            found.append(fw)
    return found or ["CPMpy"]


def snippet(text: str, limit: int = 180) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def badge(label: str, key: str = None) -> str:
    color = BADGE_COLORS.get(key or label)
    cls = "" if color else " plain"
    style = f' style="background:{color}"' if color else ""
    return f'<span class="badge{cls}"{style}>{esc(label)}</span>'


def page(title: str, prefix: str, active: str, body: str, description: str = "") -> str:
    nav_items = [
        ("index.html", "Problems", "problems"),
        ("framework.html", "Frameworks", "frameworks"),
        ("stats.html", "Stats", "stats"),
    ]
    nav = [f'<a class="brand" href="{prefix}index.html">{TITLE}</a>']
    for href, label, key in nav_items:
        cls = " active" if key == active else ""
        nav.append(f'<a class="{cls.strip()}" href="{prefix}{href}">{label}</a>')
    nav.append(f'<span class="spacer"></span>')
    nav.append(f'<a class="gh" href="{REPO_URL}" target="_blank" rel="noopener">GitHub</a>')

    if active == "index":
        hero = (
            f'<div class="hero">'
            f'<h1>{TITLE}</h1><p>{SUBTITLE}</p></div>'
        )
    else:
        hero = f'<div class="hero" style="padding-bottom:16px"><h1 style="font-size:1.4rem;margin:0">{esc(title)}</h1></div>'

    footer_head = f" · commit <code>{esc(REPO_HEAD)}</code>" if REPO_HEAD else ""
    head_desc = f'<meta name="description" content="{esc(description)}">' if description else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)} · {TITLE}</title>
{head_desc}
<link rel="stylesheet" href="{prefix}style.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css">
</head>
<body>
<header><nav>{"".join(nav)}</nav>{hero}</header>
<main>{body}</main>
<footer>Generated by <code>generate_site.py</code> from <code>dcp-bench-open.jsonl</code>{footer_head} · <a href="{REPO_URL}" target="_blank" rel="noopener">DCP-Bench Open</a></footer>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script src="{prefix}data.js"></script>
<script src="{prefix}app.js"></script>
</body>
</html>
"""


def code_block(code: str, lang: str, copy_id: str = None, head_label: str = None) -> str:
    head = ""
    if copy_id:
        head = (
            f'<div class="code-head"><span>{esc(head_label or lang)}</span>'
            f'<button type="button" data-copy="{copy_id}">Copy</button></div>'
        )
    return (
        f"{head}<pre class=\"code-block\"><code id=\"{copy_id}\" "
        f'class="language-{lang}">{esc(code)}</code></pre>'
    )


# --------------------------------------------------------------------------
# Index page (Problem view)
# --------------------------------------------------------------------------

def build_index(problems: list, stats: dict) -> None:
    categories = sorted({p["category"] for p in problems})
    frameworks = sorted({fw for p in problems for fw in p["frameworks"]})
    origins = sorted({p["origin"] for p in problems})

    cat_opts = "".join(f'<option value="{c}">{c} ({stats["categories"][c]["problems"]})</option>' for c in categories)
    fw_opts = "".join(f'<option value="{f}">{f} ({stats["frameworks"][f]})</option>' for f in frameworks)
    origin_opts = "".join(f'<option value="{o}">{o} ({stats["origins"][o]})</option>' for o in origins)

    stats_bar = f"""
    <div class="stat-row">
      <div class="stat"><div class="num">{stats["problems"]}</div><div class="lbl">problems</div></div>
      <div class="stat"><div class="num">{stats["instances"]}</div><div class="lbl">instances</div></div>
      <div class="stat"><div class="num">{len(frameworks)}</div><div class="lbl">frameworks</div></div>
      <div class="stat"><div class="num">{len(categories)}</div><div class="lbl">categories</div></div>
    </div>"""

    body = f"""
    {stats_bar}
    <div class="controls">
      <input type="search" id="filter-q" placeholder="Search problems…" autocomplete="off">
      <select id="filter-cat"><option value="">All categories</option>{cat_opts}</select>
      <select id="filter-fw"><option value="">All frameworks</option>{fw_opts}</select>
      <select id="filter-origin"><option value="">All origins</option>{origin_opts}</select>
    </div>
    <p class="result-count" id="result-count"></p>
    <div class="cards" id="cards"></div>

    <div class="section" style="margin-top:44px">
      <h2>Coverage matrix</h2>
      <div class="matrix-wrap">{coverage_matrix(problems, frameworks)}</div>
    </div>
    """

    (OUTPUT_DIR / "index.html").write_text(
        page("Problems", "", "index", body, SUBTITLE), encoding="utf-8"
    )


def coverage_matrix(problems: list, frameworks: list) -> str:
    by_cat = {}
    for p in problems:
        by_cat.setdefault(p["category"], []).append(p)

    header = "".join(f"<th>{esc(f)}</th>" for f in frameworks)
    rows = []
    for cat in sorted(by_cat):
        for p in by_cat[cat]:
            cells = []
            for fw in frameworks:
                ok = fw in p["frameworks"]
                cells.append(
                    f'<td class="{"yes" if ok else "no"}">{"✓" if ok else "·"}</td>'
                )
            rows.append(
                f'<tr><td class="cell-cat">{badge(cat, cat)}</td>'
                f'<td class="cell-id"><a href="problems/{p["id"]}.html">{esc(p["id"])}</a></td>'
                f'{"".join(cells)}</tr>'
            )
    return (
        '<table class="matrix"><thead><tr><th></th><th>problem</th>'
        f"{header}</tr></thead><tbody>{''.join(rows)}</tbody></table>"
    )


# --------------------------------------------------------------------------
# Problem pages
# --------------------------------------------------------------------------

def build_problem_page(p: dict, meta: dict, idx: int, total: int) -> None:
    pid = p["id"]
    models = f"""
      <h3>Model</h3>
      {code_block(p["model"], "python", copy_id=f"model-{idx}")}
      <h3 style="margin-top:20px">Example instance data</h3>
      {code_block(p["example_instance"] or "# No example instance data.", "python")}
    """

    instances_html = ""
    if not p["instances"]:
        instances_html = '<p class="desc">No instances available.</p>'
    else:
        for i, inst in enumerate(p["instances"], 1):
            pretty = json.dumps(inst, indent=2, ensure_ascii=False)
            instances_html += (
                f'<details class="instance"><summary>Instance {i}</summary>'
                f"<pre><code class=\"language-json\">{esc(pretty)}</code></pre></details>"
            )

    solution = code_block(
        json.dumps(p["example_solution"], indent=2, ensure_ascii=False) if p["example_solution"] else "{}",
        "json", copy_id=f"solution-{idx}",
    )
    var_chips = "".join(f'<span class="chip">{esc(v)}</span>' for v in p["decision_variables"]) or "—"

    provenance = provenance_html(meta, p)

    prev_next = ""
    if total > 1:
        prev_next = '<div style="display:flex;justify-content:space-between;gap:10px;margin-top:30px">'
        prev_next += f'<a class="btn" href="problems/{problems_list[idx - 1]["id"]}.html">← prev</a>' if idx > 0 else "<span></span>"
        prev_next += f'<a class="btn" href="problems/{problems_list[idx + 1]["id"]}.html">next →</a>' if idx < total - 1 else "<span></span>"
        prev_next += "</div>"

    body = f"""
    <p class="breadcrumbs"><a href="index.html">Problems</a> / {esc(pid)}</p>
    <h1 class="problem-title">{esc(pid)}</h1>
    <div class="tag-row">
      {badge(meta.get("category", "unknown"), meta.get("category"))}
      {''.join(badge(fw, fw) for fw in p["frameworks"])}
      {badge(p["origin"], p["origin"])}
      <span class="badge outline">{len(p["instances"])} instances</span>
      <span class="badge outline">vars: {len(p["decision_variables"])}</span>
    </div>

    <div class="card-box">
      <h3>Description</h3>
      <pre class="description">{esc(p["description"])}</pre>
    </div>

    <div class="card-box provenance">
      <h3>Provenance</h3>
      {provenance}
    </div>

    <div class="tab-bar">
      <button class="tab-btn active" type="button" data-tab="models">Models</button>
      <button class="tab-btn" type="button" data-tab="instances">Instances ({len(p["instances"])})</button>
      <button class="tab-btn" type="button" data-tab="solution">Example solution</button>
    </div>

    <div class="tab-pane active" data-pane="models">{models}</div>
    <div class="tab-pane" data-pane="instances">{instances_html}</div>
    <div class="tab-pane" data-pane="solution">
      <h3>Decision variables</h3><p>{var_chips}</p>
      <h3>Example solution</h3>{solution}
    </div>

    <div style="display:flex;gap:10px;margin-top:26px;flex-wrap:wrap">
      <a class="btn" href="{REPO_URL}/blob/main/dataset/{pid}/{pid}.cpmpy.py" target="_blank" rel="noopener">View source (GitHub)</a>
      <a class="btn" href="{REPO_URL}/blob/main/dataset/{pid}/{pid}.json" target="_blank" rel="noopener">Instances JSON</a>
      <a class="btn" href="{RAW_URL}/dataset/{pid}/{pid}.json" target="_blank" rel="noopener">Raw instances</a>
    </div>
    {prev_next}
    """

    (OUTPUT_DIR / "problems").mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "problems" / f"{pid}.html").write_text(
        page(pid, "../", "problems", body, snippet(p["description"], 160)),
        encoding="utf-8",
    )


def provenance_html(meta: dict, p: dict) -> str:
    rows = []
    if meta.get("category"):
        rows.append(f"<dt>Category</dt><dd>{badge(meta['category'], meta['category'])}</dd>")
    for key, label in (
        ("source", "Source"),
        ("source_description", "Source description"),
        ("problem_instances", "Problem instances"),
    ):
        if meta.get(key):
            rows.append(f"<dt>{label}</dt><dd>{linkify(meta[key])}</dd>")
    rows.append(f"<dt>Generated by</dt><dd>{badge(p['origin'], p['origin'])}</dd>")
    if meta.get("prompt"):
        rows.append(f"<dt>Master prompt</dt><dd>{linkify(meta['prompt'])}</dd>")
    if meta.get("solver"):
        rows.append(f"<dt>Solver</dt><dd>{esc(meta['solver'])}</dd>")
    if meta.get("solve_time"):
        rows.append(f"<dt>Solve time (s)</dt><dd>{esc(meta['solve_time'])}</dd>")
    return "<dl>" + "".join(rows) + "</dl>"


# --------------------------------------------------------------------------
# Framework view + Stats
# --------------------------------------------------------------------------

def build_frameworks(problems: list, stats: dict) -> None:
    by_fw = {}
    for p in problems:
        for fw in p["frameworks"]:
            by_fw.setdefault(fw, []).append(p)

    sections = []
    for fw in sorted(by_fw):
        items = "".join(
            f'<li><a href="problems/{p["id"]}.html">{esc(p["id"])}</a>'
            f' <span class="badge outline">{esc(p["category"])}</span></li>'
            for p in by_fw[fw]
        )
        sections.append(
            f'<div class="section"><h2>{badge(fw, fw)} {stats["frameworks"][fw]} problems</h2>'
            f'<ul class="fw-list" style="columns:3;column-gap:24px;list-style:none;padding:0">{items}</ul></div>'
        )

    body = (
        '<p class="desc" style="margin-top:0">All problems with at least one model per framework.</p>'
        + "".join(sections)
    )
    (OUTPUT_DIR / "framework.html").write_text(
        page("Framework view", "", "frameworks", body), encoding="utf-8"
    )


def build_stats(problems: list, stats: dict) -> None:
    cat_rows = "".join(
        f'<tr><td>{badge(c, c)}</td><td class="num">{s["problems"]}</td>'
        f'<td class="num">{s["instances"]}</td></tr>'
        for c, s in sorted(stats["categories"].items())
    )
    fw_rows = "".join(
        f'<tr><td>{badge(f, f)}</td><td class="num">{n}</td></tr>'
        for f, n in sorted(stats["frameworks"].items())
    )
    origin_rows = "".join(
        f'<tr><td>{badge(o, o)}</td><td class="num">{n}</td></tr>'
        for o, n in sorted(stats["origins"].items())
    )
    top = sorted(problems, key=lambda p: -len(p["instances"]))[:10]
    top_rows = "".join(
        f'<tr><td class="mono"><a href="problems/{p["id"]}.html">{esc(p["id"])}</a></td>'
        f'<td class="num">{len(p["instances"])}</td></tr>'
        for p in top
    )

    body = f"""
    <div class="stat-row">
      <div class="stat"><div class="num">{stats["problems"]}</div><div class="lbl">problems</div></div>
      <div class="stat"><div class="num">{stats["instances"]}</div><div class="lbl">instances</div></div>
      <div class="stat"><div class="num">{stats["models"]}</div><div class="lbl">models</div></div>
      <div class="stat"><div class="num">{sum(1 for p in problems if p["instances"])}</div><div class="lbl">problems with instances</div></div>
    </div>
    <div class="section"><h2>By category</h2>
      <table class="plain"><thead><tr><th>Category</th><th class="num">Problems</th><th class="num">Instances</th></tr></thead>
      <tbody>{cat_rows}</tbody></table></div>
    <div class="section"><h2>By framework</h2>
      <table class="plain"><thead><tr><th>Framework</th><th class="num">Problems</th></tr></thead>
      <tbody>{fw_rows}</tbody></table></div>
    <div class="section"><h2>By origin (generated by)</h2>
      <table class="plain"><thead><tr><th>Origin</th><th class="num">Problems</th></tr></thead>
      <tbody>{origin_rows}</tbody></table></div>
    <div class="section"><h2>Top problems by number of instances</h2>
      <table class="plain"><thead><tr><th>Problem</th><th class="num">Instances</th></tr></thead>
      <tbody>{top_rows}</tbody></table></div>
    """
    (OUTPUT_DIR / "stats.html").write_text(
        page("Stats", "", "stats", body), encoding="utf-8"
    )


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

problems_list = []


def main() -> None:
    if not DATASET_JSONL.is_file():
        raise SystemExit(
            f"Missing {DATASET_JSONL}. Run `python jsonl_convert.py` first."
        )

    if OUTPUT_DIR.exists():
        shutil.rmtree(OUTPUT_DIR)
    OUTPUT_DIR.mkdir()
    shutil.copy2(WEB_SRC / "style.css", OUTPUT_DIR / "style.css")
    shutil.copy2(WEB_SRC / "app.js", OUTPUT_DIR / "app.js")

    problems = []
    with DATASET_JSONL.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            data = json.loads(line)
            meta = parse_metadata(data.get("metadata", []))
            frameworks = detect_frameworks(data.get("model", ""))
            origin = meta.get("generated_by", "hand")
            problems.append(
                {
                    "id": data["id"],
                    "description": data.get("description", ""),
                    "model": data.get("model", ""),
                    "example_instance": data.get("example_instance", ""),
                    "instances": data.get("instances") or [],
                    "example_solution": data.get("example_solution", {}),
                    "decision_variables": data.get("decision_variables", []),
                    "frameworks": frameworks,
                    "category": meta.get("category", "other"),
                    "origin": origin,
                    "meta": meta,
                    "snippet": snippet(data.get("description", "")),
                }
            )

    global problems_list
    problems_list = problems

    stats = {
        "problems": len(problems),
        "instances": sum(len(p["instances"]) for p in problems),
        "models": sum(len(p["frameworks"]) for p in problems),
        "frameworks": {},
        "categories": {},
        "origins": {},
    }
    for p in problems:
        for fw in p["frameworks"]:
            stats["frameworks"][fw] = stats["frameworks"].get(fw, 0) + 1
        c = stats["categories"].setdefault(p["category"], {"problems": 0, "instances": 0})
        c["problems"] += 1
        c["instances"] += len(p["instances"])
        stats["origins"][p["origin"]] = stats["origins"].get(p["origin"], 0) + 1

    build_index(problems, stats)
    build_frameworks(problems, stats)
    build_stats(problems, stats)
    for idx, p in enumerate(problems):
        build_problem_page(p, p["meta"], idx, len(problems))

    # client-side index data (escaped so it can't break out of <script>)
    index_data = {
        "problems": [
            {
                "id": p["id"],
                "category": p["category"],
                "frameworks": p["frameworks"],
                "origin": p["origin"],
                "snippet": p["snippet"],
                "instances": len(p["instances"]),
            }
            for p in problems
        ]
    }
    js = "window.DCP_DATA = " + json.dumps(index_data, ensure_ascii=False).replace("<", "\\u003c") + ";\n"
    (OUTPUT_DIR / "data.js").write_text(js, encoding="utf-8")

    print(f"Generated {len(problems)} problem pages in {OUTPUT_DIR}")


if __name__ == "__main__":
    REPO_HEAD = repo_head_short()
    main()
